# Generated by Django 4.1.2 on 2023-10-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default='I was the bidder', max_length=60),
            preserve_default=False,
        ),
    ]
