# Generated by Django 4.1.2 on 2023-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_categories_remove_listing_close_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_listings',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
    ]
